include ../Makefile.defs

EXTRAFLAGS := -O2 -fno-exceptions

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
