include ../Makefile.defs

EXTRAFLAGS := -O2 -fopenmp-version=45

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
